auth/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path('login', views.LoginView.as_view(), name="login"),
    path('logout', views.LogoutView.as_view(), name="logout"),
]

movieclub/urls.py
from django.contrib import admin
from django.urls import include, path, reverse
from django.views.generic.base import RedirectView

import auth.urls
import watchlist.urls

urlpatterns = [
    path('', RedirectView.as_view(url="/watchlist/"), name="home"),
    path('admin/', admin.site.urls),
    path('auth/', include(auth.urls)),
    path('watchlist/', include(watchlist.urls)),
    # path('openapi', schemas.get_schema_view(
    #     title="Movieclub",
    #     description="",
    #     version="0.1.0"
    # )),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

watchlist/urls.py
from django.urls import path
from . import views

app_name = "watchlist"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('movie/<int:pk>', views.DetailView.as_view(), name="detail"),
    path('movie/<int:pk>/vote', views.vote, name="vote"),
    path('movie/<int:pk>/edit', views.EditView.as_view(), name="edit"),
    path('movie/<int:pk>/delete', views.delete, name="delete"),
    path('movie', views.submit, name="submit")
]

watchlist/models.py
import re

from functools import reduce
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

IMDB_ID_RE = re.compile(r'(?P<id>tt\d{7,})')
CSFD_ID_RE = re.compile(r'(?P<id>[1-9]\d*)')

def validate_imdb_id(v: str) -> bool:
    return IMDB_ID_RE.match(v)

def validate_csfd_id(v: str) -> bool:
    return CSFD_ID_RE.match(v)

class Movie(models.Model):

    class Meta:
        permissions = [
            ("moderate_movies", "Can edit other's movies and mark them as watched"),
        ]

    name = models.CharField(max_length=100)
    suggested_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    watched = models.BooleanField(default=False)
    imdb_id = models.CharField(max_length=32, blank=True, validators=[validate_csfd_id])
    csfd_id = models.CharField(max_length=32, blank=True, validators=[validate_imdb_id])

    @property
    def score(self):
        return reduce(lambda result,v: result+v.vote, self.movievote_set.filter(user__is_active=True).all(), 0)

    @property
    def seen_score(self):
        return reduce(lambda result,v: result+int(v.seen), self.movievote_set.filter(user__is_active=True).all(), 0)

    def __str__(self):
        return self.name

class MovieVote(models.Model):

    class Vote(models.IntegerChoices):
        UPVOTE = 1
        NOVOTE = 0
        DOWNVOTE = -1
    
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote = models.IntegerField(choices=Vote.choices, default=Vote.NOVOTE)
    seen = models.BooleanField(default=False, null=True)
    comment = models.TextField(blank=True)

    def __str__(self):
        return f"{self.user.username}'s vote for {self.movie.name}"

watchlist/forms.py
from django import forms

from . import models

class MovieEditForm(forms.ModelForm):
    
    class Meta:
        model = models.Movie
        fields = ["name", "suggested_by", "watched", "imdb_id", "csfd_id"]

watchlist/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponseForbidden
from django.views import generic
from django.views.decorators.http import require_http_methods, require_safe, require_POST
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from . import models

class IndexView(generic.ListView):
    template_name = "watchlist/index.html"
    model = models.Movie

    def get_queryset(self):
        qs = models.Movie.objects
        # Filter
        if self.request.GET.get("watched", False) == False:
            qs = qs.filter(watched=False)
        # Sort
        order = self.request.GET.get("sort", "score")
        if order in ('id', '-id', 'name', '-name'):
            qs = qs.order_by(order).all()
        elif order == "score" or order == "-score":
            qs = sorted(qs.all(), key=lambda x: x.score, reverse=True if order == "score" else False)
        return qs

    def get_context_data(self):
        context = super().get_context_data()
        context['can_add_movie'] = self.request.user.has_perm("watchlist.add_movie")
        context['voted_movies'] = models.Movie.objects.filter(movievote__user=self.request.user).all() if self.request.user.is_authenticated else []
        return context

class DetailView(generic.DetailView):
    model = models.Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        votes = self.object.movievote_set.filter(user__is_active=True).all()
        user_vote = None
        if self.request.user.is_authenticated:
            user_vote = votes.filter(user=self.request.user).first()
        context["votes"] = votes
        context["user_vote"] = user_vote
        return context

@login_required
@require_POST
def vote(request, pk):
    movie = get_object_or_404(models.Movie, pk=pk)
    user_vote = movie.movievote_set.filter(user=request.user).first()
    if user_vote is None:
        user_vote = models.MovieVote(movie=movie, user=request.user)
    if not request.POST.get("vote", None) in ("1", "0", "-1"):
        return HttpResponseBadRequest("Invalid vote.")
    user_vote.vote = request.POST['vote']
    user_vote.seen = request.POST.get('seen', False) == "on"    
    comment = request.POST.get('comment', '').strip()
    if comment != '' or user_vote.comment != "":
        user_vote.comment = comment
    user_vote.save()
    return HttpResponseRedirect(reverse('watchlist:index'))

class EditView(generic.DetailView):
    model = models.Movie
    template_name = "watchlist/edit.html"

    def can_edit_movie(self, request):
        return request.user.has_perm('watchlist.moderate_movies') or request.user == self.object.suggested_by

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["users"] = User.objects.filter(Q(is_active=True) | Q(id=self.object.suggested_by.id)).all() if self.request.user.has_perm("watchlist.moderate_movies") else None
        context["error"] = self.request.GET.get("error", None)
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.can_edit_movie(request):
            return HttpResponseForbidden("You cannot edit this object.")
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.can_edit_movie(request):
            return HttpResponseForbidden("You cannot edit this object.")
        if "name" in request.POST:
            name = request.POST["name"]
            if name == '':
                return HttpResponseRedirect(reverse('watchlist:edit', args=(kwargs["pk"],)) + "?error=Invalid%20name")
            self.object.name = name
        if "imdb_id" in request.POST:
            if request.POST["imdb_id"] == '':
                if self.object.imdb_id != '':
                    self.object.imdb_id = ''
            else:
                match = models.IMDB_ID_RE.search(request.POST["imdb_id"])
                if not match:
                    return HttpResponseRedirect(reverse('watchlist:edit', args=(kwargs["pk"],)) + "?error=Invalid%20IMDB%20ID")
                self.object.imdb_id = match.group()
        if "csfd_id" in request.POST:
            if request.POST["csfd_id"] == '':
                if self.object.csfd_id != '':
                    self.object.csfd_id = ''
            else:
                match = models.CSFD_ID_RE.search(request.POST["csfd_id"])
                if not match:
                    return HttpResponseRedirect(reverse('watchlist:edit', args=(kwargs["pk"],)) + "?error=Invalid%20CSFD%20ID")
                self.object.csfd_id = match.group()
        if "suggested_by" in request.POST:
            if request.user.has_perm('watchlist.moderate_movies'):
                new_suggestor = User.objects.filter(username=request.POST["suggested_by"]).first()
                if new_suggestor is None:
                    return HttpResponseBadRequest("The new suggestor doesn't exist.")
                self.object.suggested_by = new_suggestor
            # else:
            #     if request.POST["suggested_by"] != self.object.suggested_by.username:
            #         return HttpResponseForbidden("You cannot change the suggested by field.")
            self.object.save()
            return HttpResponseRedirect(reverse('watchlist:detail', args=(kwargs["pk"],)))


@login_required
@require_POST
def submit(request):
    if not request.user.has_perm("watchlist.add_movie"):
        return HttpResponseForbidden("You can't add new movies.")
    movie = models.Movie(name=request.POST["name"], suggested_by=request.user, watched=False)
    movie.save()
    return HttpResponseRedirect(reverse("watchlist:edit", args=(movie.id,)))

@login_required
@require_POST
def delete(request, pk):
    movie = get_object_or_404(models.Movie, pk=pk)
    if not (request.user.has_perm("watchlist.moderate_movies") or (
        request.user.has_perm("watchlist.delete_movie") and request.user == movie.suggested_by
    )):
        return HttpResponseForbidden("You can't delete this movie")
    movie.delete()
    return HttpResponseRedirect(reverse("watchlist:index"))

templates/watchlist/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container-lg">
    {% if error %}<div class="alert alert-warning">{{error}}</div>{% endif %}
    <form action="{% url 'watchlist:delete' movie.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete movie" class="btn btn-danger">
    </form>
    <form action="{% url 'watchlist:edit' movie.id %}" method="post">
        {% csrf_token %}
        <div>
            <label class="form-label" for="name">Movie name</label>
            <input class="form-control" id="name" name="name" value="{{movie.name}}">
        </div>
        <div>
            <label class="form-label" for="suggested_by" name="suggested_by">Suggested by</label>
            <div class="row">
                <div class="col-auto">
                    <select class="form-select" id="suggested_by" name="suggested_by">
                        {% if request.user.is_staff %}
                        {% for user in users %}
                        <option value="{{ user.username }}" {% if user.username == movie.suggested_by.username %} selected {% endif %} >{{user.username}}</option>
                        {% endfor %}
                        {% else %}
                        <option value="{{ movie.suggested_by.username }} disabled">{{movie.suggested_by.username}}</option>
                        {% endif %}
                    </select>
                </div>
            </div>
        </div>
        <div>
            <label class="form-label" for="imdb_id">IMDB id</label>
            <div class="row">
                <div class="col-auto">
                    <input class="form-control" id="imdb_id" name="imdb_id" {% if movie.imdb_id %}value="{{movie.imdb_id}}"{%endif%}>
                    <div class="form-text">ID like <code>tt5580390</code> or whole URL.</div>
                </div>
                <div class="col-3">
                    <a class="btn btn-secondary" href="https://www.imdb.com/find/?q={{movie.name}}" referrerpolicy="no-referrer" target="_blank">Search</a>
                </div>
            </div>
        </div>
        <div>
            <label class="form-label" for="csfd_id">ČSFD id</label>
            <div class="row">
                <div class="col-auto">
                    <input class="form-control" id="csfd_id" name="csfd_id" {% if movie.csfd_id %}value="{{movie.csfd_id}}"{%endif%}>
                    <div class="form-text">ID like <code>277495</code> or whole URL.</div>
                </div>
                <div class="col-3">
                    <a class="btn btn-secondary" href="https://www.csfd.cz/hledat/?q={{movie.name}}" referrerpolicy="no-referrer" target="_blank">Search</a>
                </div>
            </div>
        </div>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/watchlist/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-lg">
    <h1>Watchlist</h1>
    {% if object_list %}
    <ul>
        {% for movie in object_list %}
        <li>{% if movie.watched %}<i>{% endif %}<a href="{% url 'watchlist:detail' movie.id %}">{{movie.name}}</a>{% if movie.watched %}</i>{% endif %}{% if request.user.is_authenticated and movie not in voted_movies %}<sup>*</sup>{% endif %} &mdash; {{movie.score}}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No movies yet.</p>
    {% endif %}
    {% if can_add_movie %}
    <h2>Submit new movie</h2>
    <form action="{% url 'watchlist:submit' %}" method="post">
        {% csrf_token %}
        <label class="form-label" for="name">Movie name</label>
        <input class="form-control" type="text" id="name" name="name" required>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
    {% endif %}
</div>
{% endblock %}

templates/watchlist/movie_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container-lg">
    <h1 class="display-1">{{ movie.name }}</h1>
    <p class="text-secondary">Suggested by: {{movie.suggested_by.username}}</p>
    <div class="mb-2">
        {% if request.user.is_staff or movie.suggested_by == request.user %}<a class="btn btn-sm btn-danger" href="{% url 'watchlist:edit' movie.id %}">Edit</a>{% endif %}
        <a class="btn btn-sm btn-secondary" href="{% if movie.imdb_id %}https://www.imdb.com/title/{{movie.imdb_id}}/{%else%}https://www.imdb.com/find/?q={{movie.name}}{%endif%}" referrerpolicy="no-referrer" target="_blank">IMDB{% if movie.imdb_id == '' %}*{%endif%}</a>
        <a class="btn btn-sm btn-secondary" href="{% if movie.csfd_id %}https://www.csfd.cz/film/{{movie.csfd_id}}{%else%}https://www.csfd.cz/hledat/?q={{movie.name}}{%endif%}" referrerpolicy="no-referrer" target="_blank">ČSFD{% if movie.csfd_id == '' %}*{%endif%}</a></div>
    <h2>Votes</h2>
    {% if votes|length == 0 %}
    <p>Nobody voted yet, be first...</p>
    {% else %}
    <p>Total score: {{ movie.score }}, seen by: {{ movie.seen_score }}.
    <ul>
        {% for vote in votes %}
        <li>{{vote.user.username}} {% if vote.seen %}(seen){% endif %} &ndash; {% if vote.vote == 1 %}👍{% elif vote.vote == 0 %}No opinion{% elif vote.vote == -1 %}👎{%endif%}{% if vote.comment != "" %} &ndash; {{vote.comment}}{% endif %}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% if request.user.is_authenticated %}
    <h2>Your opinion</h2>
        <form action="{% url 'watchlist:vote' movie.id %}" method="post">
            {% csrf_token %}
            <div class="form-check">
                <input class="form-check-input" type="radio" name="vote" id="vote-upvote" value="1" {% if user_vote and user_vote.vote == 1 %} checked {% endif %}><label class="form-check-label" for="vote-upvote">Want to watch</label><br>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="vote" id="vote-novote" value="0" {% if user_vote is None or user_vote.vote == 0 %} checked {% endif %}><label class="form-check-label" for="vote-novote">No opinion</label><br>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="vote" id="vote-downvote" value="-1" {% if user_vote and user_vote.vote == -1 %} checked {% endif %}><label class="form-check-label" for="vote-downvote">Don't want to watch</label><br>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="seen" name="seen" {% if user_vote and user_vote.seen %} checked {%endif%}><label class="form-check-label" for="seen">I saw this movie already</label><br>
            </div>
            <div>
                <label class="form-check-label" for="comment">Comment</label>
                <input class="form-control" type="text" id="comment" name="comment" {% if user_vote and user_vote.comment %} value="{{user_vote.comment}}"{% endif %}>
            </div>
                <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </h2>
    {% endif %}
</div>
{% endblock %}