auth/urls.py
from django.urls import path
from . import views

app_name = "auth"
urlpatterns = [
    path('login', views.LoginView.as_view(), name="login"),
    path('logout', views.LogoutView.as_view(), name="logout"),
]

movieclub/urls.py
from django.contrib import admin
from django.urls import include, path, reverse
from django.views.generic.base import RedirectView

import auth.urls
import watchlist.urls

urlpatterns = [
    path('', RedirectView.as_view(url="/watchlist/"), name="home"),
    path('admin/', admin.site.urls),
    path('auth/', include(auth.urls)),
    path('watchlist/', include(watchlist.urls)),
    # path('openapi', schemas.get_schema_view(
    #     title="Movieclub",
    #     description="",
    #     version="0.1.0"
    # )),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

watchlist/urls.py
from django.urls import path
from . import views

app_name = "watchlist"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('movie/<int:pk>', views.DetailView.as_view(), name="detail"),
    path('movie/<int:pk>/vote', views.vote, name="vote"),
    path('movie/<int:pk>/edit', views.EditView.as_view(), name="edit"),
    path('movie/<int:pk>/delete', views.delete, name="delete"),
    path('movie', views.submit, name="submit")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>{% block title %}Movieclub{% endblock %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='icon' type="image/webp" href="{% static 'favicon.webp' %}">
    <!-- <link rel='stylesheet' type='text/css' media='screen' href='{% static "style/main.css" %}'> -->
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    {% block body %}
    {% block menu %}
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Movieclub</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-content">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-content">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'watchlist:index' %}">Watchlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="text-decoration: line-through" href="#">Reviews</a>
                    </li>
                    <li class="nav-item end-0">
                        {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}
    {% block content %}
    <p>Welcome to out little movieclub.</p> 
    {% endblock %}
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>